### ISSUE TITLE
Drop Support for Doctrine 2.2/2.3/2.4

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#23]

**Comment by caciobanu** [comment]
Doctrine guys will also drop support for 2.5: https://github.com/doctrine/doctrine2/releases/tag/v2.6.0.
Maybe it is a good idea to drop support for it also.

**Comment by cmodijk** [comment]
Thanks i never know where the doctrine team posts this info. I could not find which versions where supported.

**Comment by ruudk** [comment]
Let's not drop 2.5 directly. We wanted to upgrade from 2.5 to 2.6 but couldn't easily. The reason is that we had `json_array` columns that were created as `longtext` on MySQL 5.6 + MySQL 5.7. But since Doctrine 2.6 now supports MySQL 5.7 it wants to create `JSON` columns. So we have to migrate our existing `longtext` columns to `JSON` to not have differences between dev/test and prod.
